baseURL = "https://gophers.london"
languageCode = "en-gb"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
title = "London Gophers"
publishDir = "docs"
theme = "minimal"
[params]
  logo = "images/logo.png"
  description = "A London-based community for anyone interested in the Go programming language"
